# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e30ebed6a1e2229d307dca830c084929e43cf649e39cfe27b5b149c107f0ee55fa9d589e56217e0d81e3199b9870c35057563a0e78f9a7b0b5911cfd5e52f8d8

test:
  secret_key_base: ad84c576e4510978bdd468b4ce9ef5c71f1dce84b92e0b3949bd2199d9acb199fe17a1c4e87374147a9769d174c0a9a75e8f91af41680a01d11e31a116acd302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
